### ISSUE TITLE
Put a code first, it doesn't have a code

### ISSUE THREAD

**Issue by PIRAticaSeeker** [Nitesh-thapliyal/Github-Workshop#8]
Put a code first

_Originally posted by @PIRAticaSeeker in https://github.com/Nitesh-thapliyal/Github-Workshop/issues/5#issuecomment-839690185_
#4

**Comment by Nitesh-thapliyal** [comment]
thanks for reminding me

**Comment by Nitesh-thapliyal** [comment]
thanks once again
